DROP TABLE greetings_user_assoc_t;

DROP TABLE notification_channels_t;

DROP TABLE greetings_t;

DROP TABLE users_t;

CREATE TABLE users_t (
    user_id    NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    user_name  VARCHAR2(50),
    user_email VARCHAR2(50)
);

CREATE TABLE greetings_t (
    greeting_id       NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    greeting_type     VARCHAR2(10),
    greeting_sub_type VARCHAR2(10),
    greeting_text     VARCHAR2(4000)
);

CREATE TABLE notification_channels_t (
    notification_channel_id   NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    notification_channel_desc VARCHAR2(50),
    notification_channel_type VARCHAR2(10)
);

CREATE TABLE greetings_user_assoc_t (
    user_id                           NUMBER(19),
    greeting_next_execution_timestamp TIMESTAMP(6),
    notification_channel_id           NUMBER(19),
    CONSTRAINT gua_user_fk FOREIGN KEY ( user_id )
        REFERENCES users_t ( user_id ),
    CONSTRAINT gua_nc_fk FOREIGN KEY ( notification_channel_id )
        REFERENCES notification_channels_t ( notification_channel_id )
);